### ISSUE TITLE
RFC: Launch post deploy script

### ISSUE THREAD

**Issue by k0pernicus** [ashleygwilliams/cargo-generate#114]
For complex projects, or projects that needs, for example, system binaries, it could be great to launch a post deploy script (for example, to check or install a binary to launch the project).

This post deploy script could be in a .POST_DEPLOY file, and `cargo generate` could check if the file is available in the generated project.
If the file is available, `cargo generate` could ask to the final user if he wants to launch the .POST_DEPLOY file, or not.

Actually, I don't know if `cargo` itself contains a directive to launch a script *before* a _build_/_run_...

**Comment by epage** [comment]
https://github.com/ashleygwilliams/cargo-generate/issues/48 might also be relevant.

**Comment by epage** [comment]
Oh, looks like https://github.com/ashleygwilliams/cargo-generate/issues/18 might also be relevant.

**Comment by MarcoIeni** [comment]
This should be closed because it's a duplicate of #18 in my opinion.
k0pernicus could report its thoughts in that issue.

**Comment by k0pernicus** [comment]
Duplicate of #18
