### ISSUE TITLE
PascalCase project name variable

### ISSUE THREAD

**Issue by passcod** [ashleygwilliams/cargo-generate#117]
I started writing a template for https://github.com/passcod/notify/tree/next backends, but there's no PascalCase substitution? I want to do this:

```rust
const BACKEND_NAME: &'static str = "{{project-name}}";

pub struct {{ProjectName}} {
    //
}

impl Backend for {{ProjectName}} {
    fn name() -> &'static str {
        BACKEND_NAME
    }

    // ...
}

// etc
```

**Comment by ashleygwilliams** [comment]
sorry for the delay in respones! i would absolutely accept a PR to add this.

**Comment by passcod** [comment]
That would be ideal. Don't have lots of time right now but I might look (if
ashley is okay with this approach) during yuletide or thereabouts.

**Comment by ashleygwilliams** [comment]
it was literally forever, but this finally landed. cutting a 0.3.0 release now.
