### ISSUE TITLE
Respect branch name of template

### ISSUE THREAD

**Issue by passcod** [ashleygwilliams/cargo-generate#118]
A bit different from #94 et al: this is not about being able to choose which branch on the template repo to look at!

I wish cargo-generate would create the same main branch name as the template did. That could be for specially important reasons, like a template for the `gh-pages` branch, or for less important reasons, like wanting to avoid the word `master` in a particular community.

**Comment by ashleygwilliams** [comment]
I would absolutely accept a PR for this! Sorry for the delay in responding.

**Comment by RotationMatrix** [comment]
I'll take this one!
