### ISSUE TITLE
cargo install cargo-generate fails compiling curl-sys on windows 10

### ISSUE THREAD

**Issue by mlisanke** [ashleygwilliams/cargo-generate#122]
I've looked in both fatal errors in the output (neither had internet solution)... here's the copy of output at failure:

```
error: failed to run custom build command for curl-sys v0.4.15process didn't exit successfully:C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi\release\build\curl-sys-25e47cbb6164fbf2\build-script-build` (exit code: 101)
--- stdout
cargo:root=C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi\release\build\curl-sys-f61f6f8e7db9a41f\out
cargo:include=C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi\release\build\curl-sys-f61f6f8e7db9a41f\out\include
cargo:static=1
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "curl/lib" "-I" "curl/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_CRYPTO_AUTH" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_FTP" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS="unknown"" "-DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-o" "C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi\release\build\curl-sys-f61f6f8e7db9a41f\out\build\curl/lib\asyn-thread.o" "-c" "curl/lib/asyn-thread.c"
cargo:warning=gcc: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 1

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at '

Internal error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "curl/lib" "-I" "curl/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_CRYPTO_AUTH" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_FTP" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS="unknown"" "-DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-o" "C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi\release\build\curl-sys-f61f6f8e7db9a41f\out\build\curl/lib\asyn-thread.o" "-c" "curl/lib/asyn-thread.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).

', C:\Users\mike.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.25\src\lib.rs:2260:5
note: Run with RUST_BACKTRACE=1 for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile cargo-generate v0.2.0, intermediate artifacts can be found at C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi

Caused by:
build failed
`
```

**Comment by mlisanke** [comment]
I've looked in both fatal errors in the output (neither had internet solution)... here's the copy of output at failure:
`error: failed to run custom build command for `curl-sys v0.4.15`
process didn't exit successfully: `C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi\release\build\curl-sys-25e47cbb6164fbf2\build-script-build` (exit code: 101)
--- stdout
cargo:root=C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi\release\build\curl-sys-f61f6f8e7db9a41f\out
cargo:include=C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi\release\build\curl-sys-f61f6f8e7db9a41f\out\include
cargo:static=1
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "curl/lib" "-I" "curl/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_CRYPTO_AUTH" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_FTP" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-o" "C:\\Users\\mike\\AppData\\Local\\Temp\\cargo-install2DTZOi\\release\\build\\curl-sys-f61f6f8e7db9a41f\\out\\build\\curl/lib\\asyn-thread.o" "-c" "curl/lib/asyn-thread.c"
cargo:warning=gcc: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 1

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at '

Internal error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "curl/lib" "-I" "curl/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_CRYPTO_AUTH" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_FTP" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-o" "C:\\Users\\mike\\AppData\\Local\\Temp\\cargo-install2DTZOi\\release\\build\\curl-sys-f61f6f8e7db9a41f\\out\\build\\curl/lib\\asyn-thread.o" "-c" "curl/lib/asyn-thread.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).

', C:\Users\mike\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.25\src\lib.rs:2260:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.2.0`, intermediate artifacts can be found at `C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi`

Caused by:
  build failed
`

**Comment by mlisanke** [comment]
I didn't close the issue :-(

**Comment by DD5HT** [comment]
Do you have curl installed on your windows pc? [](https://github.com/alexcrichton/curl-rust#version-support)
also see this issue: [curl-rust/111](https://github.com/alexcrichton/curl-rust/issues/111)

**Comment by mlisanke** [comment]
yes, I run a cygwin environment:

`C:\Users\mike>curl --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
`

**Comment by ashleygwilliams** [comment]
@mlisanke sorry to hear you are running into this. i dont have a windows machine to test on and we do test this application on Appveyor but clearly we don't have good enough coverage. i would largely expect this to be an environment issue, though one we definitely would want to solve!

given some of my experience with CLI apps on windows with my other tool wasm-pack, i wonder if this isn't a path issue...

there is currently a PR to use cargo for cloning repos- i'm curious if this alleviates the problem.. (libgit2 can be... a pain sometimes). are you able to try this branch? https://github.com/ashleygwilliams/cargo-generate/pull/119

that PR also fixes several other fiddly bugs so if it also solves this that would be great.

**Comment by ashleygwilliams** [comment]
i actually just review #119 and i think it's good so i'm going to cut a release today with that in it. please let me know if it helps at all!

**Comment by longwusha** [comment]
version 0.2.1 can not be installed on windows 10

**Comment by longwusha** [comment]
more details in #127

**Comment by ashleygwilliams** [comment]
thank you for letting me know @longwusha - i'll look into it further

**Comment by alexcrichton** [comment]
Hello! I think this is slightly different than #127 due to the different error message, but I think the issue here may be the usage of cygwin instead of MinGW. The C compiler is saying that there's no input file, but my guess is that the input file is actually there but the paths aren't being communicated well. We've had a lot of trouble historically with unix-like compilers for Windows where some support Windows paths and some don't, and this is maybe a case where the cygwin compiler isn't handling the Windows path `"C:\Users\mike\AppData\Local\Temp\cargo-install2DTZOi\release\build\curl-sys-f61f6f8e7db9a41f\out\build\curl/lib\asyn-thread.o"` well?

Could you perhaps try a MinGW compiler or the MSVC target?

**Comment by ashleygwilliams** [comment]
@LandKingdom we also distribute precompiled binaries- this may end up being an easier way for you to install this tool! i'm going to close now, but if you continue to have trouble, please message and i will reopen!

**Comment by sassman** [comment]
@michelepagot I remember to have it tried once with `git-bash` and that worked nicely. But maybe there is a more powershell-ish way of doing things, not sure since I'm not a windows user.

**Comment by jockchou** [comment]
cargo:warning=ToolExecError: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "C:\\Users\\ws.WS1-0E3JBO3SKJ1\\AppData\\Local\\Temp\\cargo-install68mGjn\\release\\build\\libgit2-sys-74d17028b1ea67c8\\out\\include" "-I" "libgit
2/src/libgit2" "-I" "libgit2/src/util" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/xdiff" "-I" "libgit2/deps/pcre" "-I" "C:\\Users\\ws.WS1-0E3JBO3SKJ1\\AppData\\Local\\Temp\\cargo-install68mGjn\\release\\build\\libssh2-sys-a2f182985ecfc969\\out\\i
nclude" "-I" "C:\\Users\\ws.WS1-0E3JBO3SKJ1\\AppData\\Local\\Temp\\cargo-install68mGjn\\release\\build\\libz-sys-6f8968efe6b1748c\\out/include" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC
_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSTRSAFE_NO_DEPRECATE" "-DWIN32" "-D_WIN32_WINNT=0x0600" "-D__USE_MINGW_ANSI_STDIO=1"
"-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "C:\\Users\\ws.WS1-0E3JBO3SKJ1\\AppData\\Local\\Temp\\cargo-install68mGjn\\release\\build\\libgit2-sys-74d17028b1ea67c
8\\out\\build\\2222b295de79a116-pcre_exec.o" "-c" "libgit2/deps/pcre\\pcre_exec.c" with args gcc.exe did not execute successfully (status code exit code: 1).

  --- stderr


  error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "C:\\Users\\ws.WS1-0E3JBO3SKJ1\\AppData\\Local\\Temp\\cargo-install68mGjn\\release\\build\\libgit2-sys-74d17028b1ea67c8\\out\\include" "-I" "libgit2/src/libgit2
" "-I" "libgit2/src/util" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/xdiff" "-I" "libgit2/deps/pcre" "-I" "C:\\Users\\ws.WS1-0E3JBO3SKJ1\\AppData\\Local\\Temp\\cargo-install68mGjn\\release\\build\\libssh2-sys-a2f182985ecfc969\\out\\include" "-I"
"C:\\Users\\ws.WS1-0E3JBO3SKJ1\\AppData\\Local\\Temp\\cargo-install68mGjn\\release\\build\\libz-sys-6f8968efe6b1748c\\out/include" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10
" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSTRSAFE_NO_DEPRECATE" "-DWIN32" "-D_WIN32_WINNT=0x0600" "-D__USE_MINGW_ANSI_STDIO=1" "-DSHA1DC_NO_
STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "C:\\Users\\ws.WS1-0E3JBO3SKJ1\\AppData\\Local\\Temp\\cargo-install68mGjn\\release\\build\\libgit2-sys-74d17028b1ea67c8\\out\\build
\\2222b295de79a116-pcre_exec.o" "-c" "libgit2/deps/pcre\\pcre_exec.c" with args gcc.exe did not execute successfully (status code exit code: 1).


error: failed to compile `cargo-generate v0.20.0`, intermediate artifacts can be found at `C:\Users\ws.WS1-0E3JBO3SKJ1\AppData\Local\Temp\cargo-install68mGjn`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
