### ISSUE TITLE
generating a project with tera template

### ISSUE THREAD

**Issue by antweiss** [ashleygwilliams/cargo-generate#124]
If the template project includes [tera] (https://github.com/Keats/tera) html templates cargo-generate fails with:
```
error:  Error replacing placeholders `/root/rustlang/test/templates/index.html`
caused by: liquid: Invalid index
  with:
    index=appname
```
It seems to me generate should just ignore all placeholders except those it knows about. Maybe issue a warning,but definitely not fail on them.

**Comment by danielpclark** [comment]
That's the one Tera example that uses absolute paths for the `compile_templates!` macro.  That macro works best with relative paths and not absolute paths.  See [this discussion](https://github.com/Keats/tera/issues/359).

**Comment by antweiss** [comment]
@danielpclark thanks for noticing. however I think this relates more to the project template I created and not to the issue at hand. The issue as I understand it is that cargo-generate goes over all project  files looking for the jinja-like templating tags. If it encounters one  - it tries to replace it and that's where it stumbles upon unknown placeholder names. So this will happen if you have any templated files in your code, no matter how Tera finds them. Admittedly I'm saying all this without looking at the code. :) Will try to do that now...

**Comment by antweiss** [comment]
Looking at the code I now realize this comes from [liquid-rust](https://github.com/cobalt-org/liquid-rust). (Why it fails on that instead of just rendering an empty space as the original liquid engine does is another question)
I suppose the correct thing here would be catching the error and just verifying it's not about any of the tags known to cargo-generate. I think even a warning message would be unnecessary confusing.
@ashleygwilliams does this sound right?

**Comment by antweiss** [comment]
Thought about it some more and understood it won't work. When liquid fails - it stops processing the templates altogether. So even if the error is caught the project won't get generated correctly.

**Comment by epage** [comment]
> Looking at the code I now realize this comes from liquid-rust. (Why it fails on that instead of just rendering an empty space as the original liquid engine does is another question)

The original liquid has levels of strictness and liquid-rust is aiming to be conformant with strict mode + strict_variables + strict_filters.  I just made this explicit in the README before seeing these posts :)

> Another option that comes to mind is to add functionality that skips processing specific files. So that the whole 'templates' directory can be brought unchanged. Along the lines of .genignore. Something like .genbypass

Looks like the issue for this is a combination of https://github.com/ashleygwilliams/cargo-generate/issues/48 and https://github.com/ashleygwilliams/cargo-generate/issues/43

**Comment by antweiss** [comment]
Yep, #48 would definitely cover that. In general I like the approach of having defaults and being able to override that with configuration. I guess this issue can be closed in favour of that approach.

**Comment by ssokolow** [comment]
Bear in mind that the "just pass it through cleanly if it fails" approach would cause subtle breakages as soon as someone had a file containing only placeholders which happen to line up with the ones provided by cargo-generate.

Duck-typing the input files like that isn't not really the Rust way to do things.
