### ISSUE TITLE
Windows paths include `\\` in output instead of `\`

### ISSUE THREAD

**Issue by steveklabnik** [ashleygwilliams/cargo-generate#192]
Given these lines:

https://github.com/ashleygwilliams/cargo-generate/blob/7eb47f98c4ec0bfc670c9e6d860fd0082b35c877/src/ignoreme.rs#L61

https://github.com/ashleygwilliams/cargo-generate/blob/7eb47f98c4ec0bfc670c9e6d860fd0082b35c877/src/ignoreme.rs#L64

You end up with output like

```
Removed: "C:\\Users\\Steve Klabnik\\src\\steveklabnik-com\\.genignore"
```

Instead of

```
Removed: "C:\Users\Steve Klabnik\src\steveklabnik-com\.genignore"
```

**Comment by ashleygwilliams** [comment]
fixed by #195
