### ISSUE TITLE
Installation failed on windows 10

### ISSUE THREAD

**Issue by yorodm** [ashleygwilliams/cargo-generate#208]
Hello:

I'm having some issues building with `rustc 1.39.0 (4560ea788 2019-11-04)`. I'm using `pc-windows-gnu` both `stable` and `nightly`. Build fails with

```
  = note: ld: cannot find -lntdll
```

I'm using `mingw64/mingw-w64-x86_64-gcc 9.2.0-2` and `mingw64/mingw-w64-x86_64-crt-git 7.0.0.5553.e922460c-1`

**Comment by 2ndTaleStudio** [comment]
Hi,
I had the same issue. I just downloaded the binary from the release page: https://github.com/ashleygwilliams/cargo-generate/releases
Load the windows zip file and extract it to any folder. Copy the `cargo-generate.exe` to the `<user-home>/.cargo/bin` folder and it should work to run `cargo generate`.

**Comment by yorodm** [comment]
It seems the issue had to do with something related to one of the `sys` crates. It also seems there's a long standing issue with the `pc-windows-gnu` toolchain. I'm closing the issue since is not directly related to the project itself.
