### ISSUE TITLE
Install error: "could not find `__rt` in `quote`"

### ISSUE THREAD

**Issue by Leokuma** [ashleygwilliams/cargo-generate#216]
Right now, running `cargo install cargo-generate` is not working:

```
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> C:\Users\pc\.cargo\registry\src\github.com-1ecc6299db9ec823\failure_derive-0.1.6\src\lib.rs:107:70
    |
107 | fn display_body(s: &synstructure::Structure) -> Result<Option<quote::__rt::TokenStream>, Error> {
    |                                                                      ^^^^ could not find `__rt` in `quote`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `failure_derive`.
warning: build failed, waiting for other jobs to finish...
PS C:\WINDOWS\system32> cargo install cargo-generate======>          ] 190/230: libgit2-sys(build)
```
Apparently, [this commit](https://github.com/dtolnay/quote/commit/41543890aa76f4f8046fffac536b9445275aab26) in the crate [quote](https://github.com/dtolnay/quote) broke the crate [failure_derive](https://github.com/rust-lang-nursery/failure/tree/master/failure_derive).

There's already the following open PR to fix it: https://github.com/rust-lang-nursery/failure/pull/343.

In the meantime, there's [this workaround](https://github.com/rust-lang-nursery/failure/issues/342#issuecomment-594974002), but I'm still a beginner in Rust and I don't know how to apply it to `cargo-generate`.

**Comment by EverlastingBugstopper** [comment]
Looks like this is fixed https://github.com/rust-lang-nursery/failure/issues/342#issuecomment-595317113
