### ISSUE TITLE
Time zone is not appling

### ISSUE THREAD

**Issue by usagi** [ashleygwilliams/cargo-generate#217]
I made [this template-rust-backend-with-electron-frontend](https://github.com/usagi/template-rust-backend-with-electron-frontend) template now. But, I found `cargo-generate` cannot apply to a time zone expectedly.

My template has `{{ "now" | date: "%FT%T%z" }}` in [package.json](https://github.com/usagi/template-rust-backend-with-electron-frontend/blob/master/package.json). It be changed to `2020-03-20T07:15:54+0000`. I user expected to applying to a local time zone but it's just +0000. ( eg. Expected to "2020-03-20T16:15:54+0900" if user live in Japan. )

I think the issue is a bug of `cargo-generate`.

**Comment by k0pernicus** [comment]
Hi @usagi.
cargo-generate uses liquid for template placeholders - you can see the documentation of liquid, about the date, here: https://shopify.github.io/liquid/filters/date/

Is this liquid issue is related to your problem: https://github.com/cobalt-org/liquid-rust/issues/332 ?

**Comment by usagi** [comment]
@k0pernicus Oh, thank you for telling me!
