### ISSUE TITLE
cargo-generate generates a project even when template evaluation fails

### ISSUE THREAD

**Issue by softprops** [ashleygwilliams/cargo-generate#223]
This relates to https://github.com/softprops/rust-bin/issues/10 where there's a fix pending https://github.com/ashleygwilliams/cargo-generate/pull/213 

However a larger issue is that despite template evaluation failing with an error the project is still generated in a corrupt state. My default expectation would be that the project would not get generated if the tools processing pipeline failed.

**Comment by xoac** [comment]
Shouldn't this be closed by #225 @softprops?

**Comment by softprops** [comment]
I think so. I'll reopen another issue if it's still a problem
