### ISSUE TITLE
Document build dependencies

### ISSUE THREAD

**Issue by migerh** [ashleygwilliams/cargo-generate#42]
I wanted to install cargo-generate in my WSL Ubuntu and ran into a few problems. One was with the openssl-sys crate that needs at least two additional packages that weren't installed on my system. The other was libssh2-sys that needs cmake. So in order to install cargo-generate I had to

    sudo apt-get install pkg-config libssl-dev cmake

first. The openssl-sys crate [has a guide](https://crates.io/crates/openssl-sys) on how to install the build dependencies on various systems. I don't know if cmake is needed on all systems.

**Comment by ashleygwilliams** [comment]
hey @migerh - i'm working on OSX and the travis tests run on windows and travis(linux) and i haven't run into this issue- tho i totally believe that it is one for some operating systems. i would love a PR to document this- the key work left to be done is to figure out what systems need it!

if you make a PR to throw a warning in the readme stating that you may need to `sudo apt-get install pkg-config libssl-dev cmake` i would happily accept, and in the meantime i'll leave this open and see if we can't get a better sense of what group of OSs need this!

**Comment by migerh** [comment]
Travis has a few things pre-installed, on ubuntu trusty `libssl-dev` for example is one of them:

```
$ docker run --rm -ti travisci/ci-garnet:packer-1512502276-986baf0 dpkg -l libssl-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libssl-dev:amd 1.0.1f-1ubun amd64        Secure Sockets Layer toolkit - de
```

In fact, the WSL ubuntu was the first time I ran into any trouble installing cargo-generate. All my other systems installed it just fine. OS X went through because openssl was already brewed because of python.

With a clean ubuntu docker container I was able to check what is required on ubuntu:

    build-essentials libssl-dev pkg-config cmake zlib1g-dev

`build-essentials` could possibly be broken down into smaller dependencies but it's generally not bad to have for developers. `libssl-dev` and `pkg-config` are for `openssl-sys`, `cmake` and `zlib1g-dev` are for `libssh2-sys` .

**Comment by migerh** [comment]
I'd love to but probably won't have a chance before sunday.

ashley williams <notifications@github.com> schrieb am Fr., 20. Juli 2018,
13:18:

**Comment by ashleygwilliams** [comment]
closed by https://github.com/ashleygwilliams/cargo-generate/pull/45#pullrequestreview-139443049
