### ISSUE TITLE
RFC: Only replace variables in files with specific extension?

### ISSUE THREAD

**Issue by killercup** [ashleygwilliams/cargo-generate#43]
## Context

Currently, cargo-generate tries to find and replace all `{{ blocks }}` in all files. This is the most trivial implementation, but not necessarily the best or most user friendly one.

As written in <https://github.com/ashleygwilliams/cargo-generate/issues/14#issuecomment-405957200> and <https://github.com/ashleygwilliams/cargo-generate/issues/40#issuecomment-406536791>, an alternative might be to instead only consider files whose names match a specific pattern as templates.

## Questions

- Should we filter by file extensions?
- If yes, which ones?
- If yes, where to define this extension? (Also cf. #48)

## Possibles solutions

- Yes, with `.template`

    (Because it's pretty obvious and also not bound to any implementation. It has the added advantage that projects that already have `.hbs` or `.liquid` files are unlikely to conflict.)

- Yes, defined in config file (cf. #48), defaulting to `.tplt`

- No

## Notes

The implementation should be pretty straightforward. I assume it's a matter of expanding [this condition](https://github.com/ashleygwilliams/cargo-generate/blob/9850761ca2895f38a96d73e945ee476e590181f1/src/template.rs#L34-L36) and adding a test or two.

**Comment by rahul-thakoor** [comment]
Hey there!

Yes, we could have a file that lists all the files to be parsed.
