### ISSUE TITLE
Reconsider subcommand name

### ISSUE THREAD

**Issue by theduke** [ashleygwilliams/cargo-generate#52]
This might be trivial bike-shedding territory, but I'm not in love with the naming.
`generate` is very generic and doesn't communicate the intent all that clearly.

Some options I would like more:

* bootstrap
* kickstart 

Actually, having this integrated into "cargo new"  might also be a cool option, although one that would probably take some time to get right.
Eg:
`cargo new --template=diesel-rs/diesel`

**Comment by ashleygwilliams** [comment]
hey! the long term goal is to get this integrated into cargo, but we'd like to spend sometime getting feedback first! as a result i don't think we'll bike shed the name.
