### ISSUE TITLE
provide short "gen" version of "generate" command

### ISSUE THREAD

**Issue by ZhangHanDong** [ashleygwilliams/cargo-generate#53]
Follow Rust's short philosophy，like `function`  to `fn`

`cargo-generate` change to `cargo-g` maybe better?

**Comment by ashleygwilliams** [comment]
i'm not a fan of `cargo-g` *but* i think we can make a short alias for cargo-gen ;)

**Comment by ZhangHanDong** [comment]
@ashleygwilliams Thanks

**Comment by ashleygwilliams** [comment]
closed by #72

**Comment by ZhangHanDong** [comment]
Cool
