### ISSUE TITLE
suggestion: cargo new --template <crate>:<template>

### ISSUE THREAD

**Issue by I60R** [ashleygwilliams/cargo-generate#54]
Rationale:
1) Generating project code from templates is a basic and common task, and I think it should be provided by default rather than be shipped as external tool
2) It could be even easier for newcomers to get started with specific templates, since there will be less steps to do and less specific things to remember
3) It could be easier to provide project templates, since that assumes well defined place for them inside of crate (e.g. `templates` folder), and that will not require additional git setup ceremony
4) This will be more convenient, since `cargo new` already acts like code generator and features like `--name` and `--vcs` might be effectively combined and reused here
5) Examples are already handled by cargo, as well as tests, docs, benchmarks and other things that belongs to project, so it's expected to handle templates in the same way

**Comment by ashleygwilliams** [comment]
this is our longterm intention! we'd like to start independent tho, so that we have the opportunity to churn and experiment more- we do completely agree tho that eventually merging with cargo is the way to go :)
