### ISSUE TITLE
warn user if we change given name's case

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/cargo-generate#65]
right now, we receive a name from the user, force it to kebab case, and make the project. we should check the user's entered name and warn them if we are changing the case of the name they passed.

**Comment by epage** [comment]
Other possible approaches
- Templates have validation code in a [hook](https://github.com/ashleygwilliams/cargo-generate/issues/18) that errors on an invalid name
- Ask for a human friendly name and then ask for the package name, offering a default that is a `heck` slug of the human friendly name.

**Comment by k0pernicus** [comment]
@ashleygwilliams Maybe I can work on that issue - if you are agree (and no one is already working on this one :))

**Comment by ashleygwilliams** [comment]
go for it @k0pernicus ! :)

**Comment by ashleygwilliams** [comment]
closed by #84
