### ISSUE TITLE
Support conditional tags in templates

### ISSUE THREAD

**Issue by epage** [ashleygwilliams/cargo-generate#68]
Example from #51 

Cargo.toml
```liquid
{% if use_serde %}
serde = "1.*"
serde_derive = "1.*"
{% endif %}
```

lib.rs
```liquid
{% if db_type = "postgres" % } 
type Connection = diesel::pg::PgConnection;
{% elseif db_type = "mysql" % } 
...
{% endif %}
```

Relevant tags
- if, elseif, else, unless for boolean ["choices"](https://github.com/ashleygwilliams/cargo-generate/issues/17)
- case / when for richer ["choices"](https://github.com/ashleygwilliams/cargo-generate/issues/17).

**Comment by ashleygwilliams** [comment]
hey! so- this is a complex feature request and as i said in the last issue filed on this- it would be great if you could build a template meant to be used with this project that absolutely requires this feature. the example used seems to suggest some sort of pluggable web app framework, that i don't think exists in rust at the moment. either way, if you can show me a working template that folks are using that would benefit from this i would be happy to look into implementing this feature!
