### ISSUE TITLE
should we build binaries?

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/cargo-generate#7]
curious what you think @killercup - not sure if binaries really make sense for a cargo add-on, but interested in your thoughts.

**Comment by killercup** [comment]
One the one hand, it can't really hurt to provide pre-built binaries for some common platforms.

On the other hand, cargo subcommands is literally what we say `cargo install` should be used for 🤷‍♂️

**Comment by ashleygwilliams** [comment]
yeah ok- i'm gonna defer building binaries for now. doesn't seem too useful. one day, if someone comes through here and re comments on this issue, i'll open it up and do it ;)
