### ISSUE TITLE
update liquid dep, document date functionality

### ISSUE THREAD

**Issue by deg4uss3r** [ashleygwilliams/cargo-generate#70]
While setting up my environment and templates I noticed a few areas that would be helpful to have a `{{date}}` placeholder. Might also be nice to have sub-date strings like `{{year}}` as well (e.g. for license, info). 

Related to #46

**Comment by ashleygwilliams** [comment]
i def see how year would be extremely useful... can you say more about the examples that would require a full date? thanks!

**Comment by deg4uss3r** [comment]
>  can you say more about the examples that would require a full date? thanks! 

The example I had though of yesterday was I had a "created on {{date}}" in my comments at the top of a test repository along with the description of what the application did. That's as far as I got! 

I really like @epage's idea, allow the user to control it and give them as much info to widdle down themselves. I did a [quick start](https://github.com/deg4uss3r/cargo-generate/blob/date_placeholder/src/placeholders.rs) of this yesterday to learn how `cargo-generate` was made I added another module called `placeholders` thinking there might be a few more that people would want to see.

**Comment by ashleygwilliams** [comment]
cool! yeah my main issue is trying to keep things simple, potentially surprisingly, choice is not always user--friendly. regardless, if this is something we could get out of the box, e.g. rust-liquid could support it, that'd be fantastic :) - anyone know folks from that team? if not, i can reach out

**Comment by epage** [comment]
I am the maintainer of liquid-rs :).  In my rust-time, I am first trying to get some stuff out for CLI-WG.  After that I could look at making this work unless someone wants to be mentored on this.

This will require two parts
- add "now" support
- expose the `date` filter so you can add it without having to add all of the other filters.

**Comment by ashleygwilliams** [comment]
well that is *incredibly* convenient :) are you interested in filing the issues? let me know- otherwise i can. i'll work on trying to solicit a contributor, worst case scenario, i can tackle this, probably next week.

**Comment by epage** [comment]
Created https://github.com/cobalt-org/liquid-rust/issues/181

My expectation is I'll be able to get this by Saturday.

**Comment by epage** [comment]
While waiting for my CI for another PR, I got https://github.com/cobalt-org/liquid-rust/issues/181 submitted and liquid v0.15.0 released (breaking change was from a different PR, changing f32->f64)

**Comment by epage** [comment]
To take advantage of this
- Update liquid
- Add filter

Adding the filter will roughly be
```rust
fn engine() -> liquid::Parser {
    liquid::ParserBuilder::new()
        .filter("date", liquid::filters::date as interpreter::FnFilterValue)
        .build()
}
```

**Comment by killercup** [comment]
I'm not entirely convinced this is a good way to implement this – simply, because we are kind of setting the decision to use liquid (or a very similar impl) in stone once people use this feature.

But, it _is_ very nice to have. Let's for for it.

**Comment by ashleygwilliams** [comment]
@killercup since we are pre 1.0 i am happy to add the functionality to see how folks like it, if by 1.0 we decide we need to implement it a different way, i think so long as we cover the feature, we can change the interface if we decide we need to. i feel very comfy saying, yes let's support dates, exactly what the interface is is something i think we can be flexible about.

**Comment by killercup** [comment]
Agreed. That was basically my reason to write "Go for it", too :)
