### ISSUE TITLE
Support repository banches

### ISSUE THREAD

**Issue by deg4uss3r** [ashleygwilliams/cargo-generate#71]
I set my templates up in one repository and was branching for differences in my templates (see [cli-templates](https://github.com/deg4uss3r/cli-template) for my rough drafts); however, as of now `cargo-generate` only supports main branch templating. 

To me it makes sense to have all my custom templates in one repostory but have the ability to call them by branch, vice several different repositories. Also it might make sense for offical templates to have branches with different specializations or layouts.

Related to RFC #47

**Comment by ashleygwilliams** [comment]
@deg4uss3r this is a good call and shouldn't be much overhead over what we are doing using git anyways! thanks for filing :)

**Comment by deg4uss3r** [comment]
Thanks @ashleygwilliams! If you'd like I could try to help with this issue :)

**Comment by ashleygwilliams** [comment]
that'd be great @deg4uss3r ! feel free to file a WIP PR to start, and always happy to help with questions if you have any :)

**Comment by ashleygwilliams** [comment]
closed by #94
