### ISSUE TITLE
add `-n` short alias for `--name`

### ISSUE THREAD

**Issue by DD5HT** [ashleygwilliams/cargo-generate#73]
There is already a short version of generate, why don't we add -n for name and -g for git?
Example:
`cargo gen -g https://github.com/user/template.git -n foo`

**Comment by killercup** [comment]
I assume the reason you want this is to type less? Then I'd rather see this:

No `--git` or `-g`, but allow passing _something_
that can we can interpret (a git-parsable URL for now) as a free argument.
Also, omit the `-n` completely and wait for cargo-generate to prompt you :)

**Comment by ashleygwilliams** [comment]
i mostly agree with @killercup - but in the sense of actionable requests from this- @killercup do you mind the `-n` short for `--name`? we can punt on the `--git` sitch til later (open another issue or something...)

**Comment by killercup** [comment]
-n is fine

**Comment by ashleygwilliams** [comment]
closed by #77
