### ISSUE TITLE
split into shallow main and throw functionality in lib

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/cargo-generate#81]
there is a universe (#80) where  i would like to use this tool as a library. it's a pretty common pattern for cli apps to have a shallow main that primarily uses a lib. we're real close to that, but we need a lib.rs to get it over the hump.

**Comment by DD5HT** [comment]
I've a working Prototype with a shallow main. But I still have to improve the error handling in the library before I can push it. I've also refactored some of the logical blocks into separate functions.
`src/bin/client.rs`
```rust
#[macro_use]
extern crate quicli;
extern crate cargo_generate;

use cargo_generate::{Cli, generate};
use quicli::prelude::StructOpt;

main!(|_cli: Cli| {
    generate(_cli);
});
```

**Comment by ashleygwilliams** [comment]
cool! if you want to start a WIP PR (work-in-progress PR) i'm happy to work with you on it- we may end up needing to take quicli out... i think that's fine. also we can have a top level ? in main :D - that might help! (it's a new feature so i'm not sure if you knew about it)
