### ISSUE TITLE
Do some cleanup on the template

### ISSUE THREAD

**Issue by TeXitoi** [ashleygwilliams/cargo-generate#82]
Hi!

I would need to remove some files from the template.

Usecase: migrate https://github.com/TeXitoi/blue-pill-quickstart to cargo-generate

Some files are here only for the purpose of explaining the repository. I'd like these files to be deleted when using `cargo generate`. In this case, the files to remove are `LICENSE` `README.md` and `st-link-v2-blue-pill.jpg`.

**Comment by DD5HT** [comment]
So you want something like .gitignore for cargo generate.  #48 a config file could also solve this problem.

**Comment by ashleygwilliams** [comment]
closed by #96
