### ISSUE TITLE
Git submodules

### ISSUE THREAD

**Issue by roblabla** [ashleygwilliams/cargo-generate#83]
Currently, cargo-generate ignores git submodules (does not clone them recursively). I'm working on a Rust toolchain for the Nintendo Switch, and I'd like to have my template contain a git submodule for my fork of the rust stdlibd. 

I believe cargo generate should clone templates recursively.

**Comment by ashleygwilliams** [comment]
i totally think we should do this! my only thought is- should this be default behavior or a flag- any thoughts @roblabla or @killercup ? i can't imagine that doing it by default would cause issue, but i also rarely use git submodules so don't have a ton of experience to draw on here. open to either!

**Comment by roblabla** [comment]
By default, git does not clone submodules because it can take a large amount of time to clone, and might not be necessary.

But in the context of a template, IMO the default should be to clone it. I can't imagine a case where a template would have a submodule the author didn't intend to get cloned. Curious to hear if anyone has a use-case for a non-cloned submodule in a template though.

**Comment by ashleygwilliams** [comment]
yeah i tend to agree with you @roblabla - let's leave this open for a few days and see if there's any comments. otherwise i'm quite happy to accept a PR for this (if you are interested- go for it!)

**Comment by k0pernicus** [comment]
I just checked the `git2-rs` crate and there is a method that clone the repository *and* the submodules recursively: https://docs.rs/git2/0.7.5/git2/struct.Repository.html#method.clone_recurse

Maybe, first, we can check if the repository contains submodules - if it does, we can use `clone_recurse`, otherwise we can just `clone` it.  
The problem here is: how can we check if the repository contains submodules if we can't clone it...  
Maybe an option in cloning it?
Like `cargo generate --git https://github.com/user/example --with-submodules --name myexample`?

**Comment by k0pernicus** [comment]
@ashleygwilliams Actually, I just read your thoughts about removing `libgit2` [here](https://github.com/ashleygwilliams/cargo-generate/issues/80)...  
So the best solution here may be the second one.

**Comment by k0pernicus** [comment]
No problem.
I will create a PR for the `clone_reverse` solution if you are ok with that.

**Comment by ashleygwilliams** [comment]
yup! that's great. i should note that i was planning on doing a release today- let me know what your time constraints are. if we think we can get this in today that'd be awesome, but i don't want to put too much pressure. let me know!

**Comment by k0pernicus** [comment]
@ashleygwilliams I can work on it right now ;)

**Comment by ashleygwilliams** [comment]
closed by #104 - thanks @k0pernicus ! @roblabla we'll be making a release tomorrow- please try that out as it should resolve your issue! closing this now, please file an issue if you run into any problems!
