### ISSUE TITLE
produce binaries

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/cargo-generate#99]
in prep for https://github.com/rustwasm/wasm-pack/issues/373 we should build binaries - starting with tomorrow release of 0.2.0

**Comment by killercup** [comment]
I've just added [trust](https://github.com/japaric/trust) to one of my projects ([here](https://github.com/killercup/waltz/commit/86fd70cd1ce3cd5dbb65902be6f2e555e9aff88b) and [here](https://github.com/killercup/waltz/commit/5a38e7d3ddb792fc025a4ada468c82b5549fadee)) – AMA
